USE [DADOSPRO]
GO
/****** Object:  StoredProcedure [dbo].[SP_BALANCO_DE_MASSA_PASSO_9]    Script Date: 10/08/2021 17:22:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/******************************************************************************
* PROCEDURE : SP_BALANCO_DE_MASSA_PASSSO_9	  								  *
* OBJETIVO  : Processo gerador do BM										  *
* AUTOR     : Carlos Torres                                                   *
* DATA      : 26/03/2014                                                      *
* OBSERVACAO:                                                                 * 
*                                                                             *
*---------------------------------ALTERACOES----------------------------------*
* DATA       AUTOR       OBJETIVO                                             *
*----------- ----------- -----------------------------------------------------*
*                                                                             *
******************************************************************************/
ALTER PROCEDURE [dbo].[SP_BALANCO_DE_MASSA_PASSO_9]
AS
BEGIN
	IF ISNULL(OBJECT_ID('TEMP_RESUMO_BM'), 0) <> 0
	BEGIN
		DROP TABLE TEMP_RESUMO_BM
	END

	CREATE TABLE #TEMP_RESUMO_ARMAZEM
	(
		ID_LOCAL	VARCHAR(2)	,
		NM_ARMAZ	VARCHAR(50)	,
		ID_ARMAZ	VARCHAR(10)
	)

	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('01','CQ','1-96')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('96','CQ','1-96')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('02','MP LOCAL','2-11-81')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('11','MP LOCAL','2-11-81')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('81','MP LOCAL','2-11-81')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('31','MP TERCEIROS','31-32')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('32','MP TERCEIROS','31-32')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('21','PA','21-25')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('25','PA','21-25')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('51','ASSISTENCIA TECNICA','51-52-53')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('52','ASSISTENCIA TECNICA','51-52-53')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('53','ASSISTENCIA TECNICA','51-52-53')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('93','REFUGO','93')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('91','DEVOLUCAO/TROCA MP','91-92')
	INSERT INTO #TEMP_RESUMO_ARMAZEM (ID_LOCAL,NM_ARMAZ,ID_ARMAZ) VALUES ('92','DEVOLUCAO/TROCA MP','91-92')

	CREATE TABLE TEMP_RESUMO_BM
	(
		ID_LOCAL	VARCHAR(10)	,
		NM_ARMAZ	VARCHAR(50)	,
		UN_NEGOCIO	VARCHAR(9)	,
		VL_LOCAL	DECIMAL(12,4),
		VL_EM3OS	DECIMAL(12,4),
		VL_TOTAL	DECIMAL(12,4)
	)

	INSERT INTO TEMP_RESUMO_BM
	(
		ID_LOCAL	,
		NM_ARMAZ	,
		UN_NEGOCIO	,
		VL_LOCAL	,
		VL_EM3OS	,
		VL_TOTAL	
	  ) SELECT 
		ID_LOCAL	,
		NM_ARMAZ	,
		UN_NEGOCIO		,
		SUM(VL_LOCAL)	AS VL_LOCAL	,
		SUM(VL_EM3OS)	AS VL_EM3OS	,
		SUM(VL_TOTAL)	AS VL_TOTAL
		FROM (
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM BLM
			WHERE ID_LOCAL IN ('01','96')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_DAIHATSU_FILIAL_01 BLM
			WHERE ID_LOCAL IN ('01','96')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL BLM
			WHERE ID_LOCAL IN ('01','96')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL_SP BLM
			WHERE ID_LOCAL IN ('01','96')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_ACTION_VARGINHA BLM
			WHERE ID_LOCAL IN ('01','96')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_EXTREMA BLM
			WHERE ID_LOCAL IN ('01','96')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_FILIAIS BLM
			WHERE ID_LOCAL IN ('01','96')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART BLM
			WHERE ID_LOCAL IN ('01','96')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM BLM
			WHERE ID_LOCAL IN ('02','11','81')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_DAIHATSU_FILIAL_01 BLM
			WHERE ID_LOCAL IN ('02','11','81')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL BLM
			WHERE ID_LOCAL IN ('02','11','81')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL_SP BLM
			WHERE ID_LOCAL IN ('02','11','81')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_ACTION_VARGINHA BLM
			WHERE ID_LOCAL IN ('02','11','81')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_EXTREMA BLM
			WHERE ID_LOCAL IN ('02','11','81')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_FILIAIS BLM
			WHERE ID_LOCAL IN ('02','11','81')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART BLM
			WHERE ID_LOCAL IN ('02','11','81')

		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM BLM
			WHERE ID_LOCAL IN ('31','32')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_DAIHATSU_FILIAL_01 BLM
			WHERE ID_LOCAL IN ('31','32')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL BLM
			WHERE ID_LOCAL IN ('31','32')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL_SP BLM
			WHERE ID_LOCAL IN ('31','32')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_ACTION_VARGINHA BLM
			WHERE ID_LOCAL IN ('31','32')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_EXTREMA BLM
			WHERE ID_LOCAL IN ('31','32')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_FILIAIS BLM
			WHERE ID_LOCAL IN ('31','32')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART BLM
			WHERE ID_LOCAL IN ('31','32')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM BLM
			WHERE ID_LOCAL IN ('21','25')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_DAIHATSU_FILIAL_01 BLM
			WHERE ID_LOCAL IN ('21','25')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL BLM
			WHERE ID_LOCAL IN ('21','25')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL_SP BLM
			WHERE ID_LOCAL IN ('21','25')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_ACTION_VARGINHA BLM
			WHERE ID_LOCAL IN ('21','25')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_EXTREMA BLM
			WHERE ID_LOCAL IN ('21','25')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_FILIAIS BLM
			WHERE ID_LOCAL IN ('21','25')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART BLM
			WHERE ID_LOCAL IN ('21','25')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM BLM
			WHERE ID_LOCAL IN ('93')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_DAIHATSU_FILIAL_01 BLM
			WHERE ID_LOCAL IN ('93')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL BLM
			WHERE ID_LOCAL IN ('93')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL_SP BLM
			WHERE ID_LOCAL IN ('93')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_ACTION_VARGINHA BLM
			WHERE ID_LOCAL IN ('93')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_EXTREMA BLM
			WHERE ID_LOCAL IN ('93')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_FILIAIS BLM
			WHERE ID_LOCAL IN ('93')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART BLM
			WHERE ID_LOCAL IN ('93')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM BLM
			WHERE ID_LOCAL IN ('91','92')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_DAIHATSU_FILIAL_01 BLM
			WHERE ID_LOCAL IN ('91','92')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL BLM
			WHERE ID_LOCAL IN ('91','92')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL_SP BLM
			WHERE ID_LOCAL IN ('91','92')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_ACTION_VARGINHA BLM
			WHERE ID_LOCAL IN ('91','92')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_EXTREMA BLM
			WHERE ID_LOCAL IN ('91','92')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_FILIAIS BLM
			WHERE ID_LOCAL IN ('91','92')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART BLM
			WHERE ID_LOCAL IN ('91','92')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM BLM
			WHERE ID_LOCAL IN ('51','52','53')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_DAIHATSU_FILIAL_01 BLM
			WHERE ID_LOCAL IN ('51','52','53')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL BLM
			WHERE ID_LOCAL IN ('51','52','53')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_MERCABEL_SP BLM
			WHERE ID_LOCAL IN ('51','52','53')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_ACTION_VARGINHA BLM
			WHERE ID_LOCAL IN ('51','52','53')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_EXTREMA BLM
			WHERE ID_LOCAL IN ('51','52','53')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART_FILIAIS BLM
			WHERE ID_LOCAL IN ('51','52','53')
		UNION ALL
			SELECT
				(SELECT ID_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'ID_LOCAL'	,
				(SELECT NM_ARMAZ FROM #TEMP_RESUMO_ARMAZEM AUX WHERE BLM.ID_LOCAL=AUX.ID_LOCAL) AS 'NM_ARMAZ'	,
				UN_NEGOCIO		,
				TT_CUSTO	AS VL_LOCAL	,
				EM_CUSTO	AS VL_EM3OS	,
				TT_CUSTO+EM_CUSTO			AS VL_TOTAL	
			FROM TEMP_MOVIMENTOS_BM_PROART BLM
			WHERE ID_LOCAL IN ('51','52','53')

		) TMP
		GROUP BY ID_LOCAL, NM_ARMAZ, UN_NEGOCIO

	DELETE FROM TEMP_RESUMO_BM 
		WHERE VL_LOCAL + VL_EM3OS = 0
END