USE [DADOSPRO]
GO
/****** Object:  StoredProcedure [dbo].[SP_REL_PCP_DETALHE_APONTAMENTO_DE_HORAS_PROTHEUS]    Script Date: 29/07/2021 14:00:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/******************************************************************************
* PROCEDURE : SP_REL_PCP_DETALHE_APONTAMENTO_DE_HORAS_PROTHEUS				  *
* OBJETIVO  : Relatorio de horas improdutivas                   			  *
* AUTOR     : Carlos Torres                                                   *
* DATA      : 25/05/2017                                                      *
* OBSERVACAO: Procedure usada pela rotina PCPHOROPE							  * 
*							                                                  *
*---------------------------------ALTERACOES----------------------------------*
* DATA       AUTOR       OBJETIVO                                             *
*----------- ----------- -----------------------------------------------------*
* EXEC SP_REL_PCP_DETALHE_APONTAMENTO_DE_HORAS_PROTHEUS '','','20170705','20170705','' *
******************************************************************************/
ALTER PROCEDURE [dbo].[SP_REL_PCP_DETALHE_APONTAMENTO_DE_HORAS_PROTHEUS]
			@CFILOPERADOR	VARCHAR(06),
			@CFILRECURSO	VARCHAR(07),
			@CDTAPOINI		VARCHAR(10),
			@CDTAPOFIM		VARCHAR(10),
			@CSUPERVISOR	VARCHAR(06)
AS
BEGIN
	--DECLARE	@CFILOPERADOR	VARCHAR(06),
	--		@CFILRECURSO	VARCHAR(07),
	--		@CDTAPOINI		VARCHAR(10),
	--		@CDTAPOFIM		VARCHAR(10)

	--SET	@CFILOPERADOR = '000273'
	--SET @CFILRECURSO = ''
	--SET @CDTAPOINI = '20170706'
	--SET @CDTAPOFIM = '20170706'

	SELECT 
		CBI_DESCRI
		,CBH_HRINI AS HR_INICIO
		,CBH_HRFIM AS HR_FINAL
		,0 AS DIF
		,CBH_OPERAD AS ID_OPERADOR
		,CBH_TRANSA AS OPERACAO
		,CBH_RECUR AS RECURSO
		,CONVERT(VARCHAR(10),CONVERT(DATE,CBH_DTINI),103) AS DT_INICIO
		,CONVERT(VARCHAR(10),CONVERT(DATE,CBH_DTFIM),103) AS DT_FINAL
		,CB1_NOME,C2_PRODUTO
		,CBH.R_E_C_N_O_
	FROM CBH040 CBH WITH(NOLOCK)
	INNER JOIN CBI040 CBI WITH(NOLOCK) ON CBI_FILIAL = CBH_FILIAL AND CBI_CODIGO = CBH_TRANSA 
	INNER JOIN CB1040 CB1 WITH(NOLOCK) ON CB1_FILIAL = CBH_FILIAL AND CB1_CODOPE = CBH_OPERAD AND CB1.D_E_L_E_T_=''
	INNER JOIN SC2040 SC2 WITH(NOLOCK) ON C2_FILIAL = CBH_FILIAL AND C2_NUM=LEFT(CBH_OP,6) AND C2_ITEM=SUBSTRING(CBH_OP,7,2) AND C2_SEQUEN=RIGHT(LTRIM(RTRIM(CBH_OP)),3) AND SC2.D_E_L_E_T_=''
	WHERE CBH_FILIAL = '02'
	AND CBH.D_E_L_E_T_ <> '*' AND CBI.D_E_L_E_T_ <> '*'
	AND CBH_DTINI>=@CDTAPOINI AND CBH_DTFIM <= @CDTAPOFIM  
	AND CBH_OPERAC = '01'
	AND CBH_TRANSA >= '50'
	AND CBH_HRFIM !=''
	AND ((CBH_RECUR = @CFILRECURSO AND @CFILRECURSO!='') OR @CFILRECURSO='')
	AND ((CBH_OPERAD = @CFILOPERADOR AND @CFILOPERADOR!='') OR @CFILOPERADOR='')
	AND ((CB1.CB1_SUPERV=@CSUPERVISOR AND @CSUPERVISOR!='') OR @CSUPERVISOR='')
	UNION ALL
	SELECT 
		'PRODUCAO' AS CBI_DESCRI
		,CBH_HRINI AS HR_INICIO
		,CBH_HRFIM AS HR_FINAL
		,0 AS DIF
		,CBH_OPERAD AS ID_OPERADOR
		,CBH_TRANSA AS OPERACAO
		,CBH_RECUR AS RECURSO
		,CONVERT(VARCHAR(10),CONVERT(DATE,CBH_DTINI),103) AS DT_INICIO
		,CONVERT(VARCHAR(10),CONVERT(DATE,CBH_DTFIM),103) AS DT_FINAL
		,CB1_NOME,C2_PRODUTO
		,CBH.R_E_C_N_O_
	FROM CBH040 CBH WITH(NOLOCK)
	INNER JOIN CBI040 CBI WITH(NOLOCK) ON CBI_FILIAL = CBH_FILIAL AND CBI_CODIGO  = CBH_TRANSA 
	INNER JOIN CB1040 CB1 WITH(NOLOCK) ON CB1_FILIAL = CBH_FILIAL AND CB1_CODOPE = CBH_OPERAD AND CB1.D_E_L_E_T_=''
	INNER JOIN SC2040 SC2 WITH(NOLOCK) ON C2_FILIAL = CBH_FILIAL AND C2_NUM=LEFT(CBH_OP,6) AND C2_ITEM=SUBSTRING(CBH_OP,7,2) AND C2_SEQUEN=RIGHT(LTRIM(RTRIM(CBH_OP)),3) AND SC2.D_E_L_E_T_=''
	WHERE CBH_FILIAL = '02'
	AND CBH.D_E_L_E_T_ <> '*' AND CBI.D_E_L_E_T_ <> '*'
	AND CBH_DTINI>=@CDTAPOINI AND CBH_DTFIM <= @CDTAPOFIM  
	AND CBH_OPERAC = '01'
	AND CBH_TRANSA = '02'
	AND CBH_HRFIM !=''
	AND ((CBH_RECUR = @CFILRECURSO AND @CFILRECURSO!='') OR @CFILRECURSO='')
	AND ((CBH_OPERAD = @CFILOPERADOR AND @CFILOPERADOR!='') OR @CFILOPERADOR='')
	AND ((CB1.CB1_SUPERV=@CSUPERVISOR AND @CSUPERVISOR!='') OR @CSUPERVISOR='')
	ORDER BY CBH_RECUR,CBH_OPERAD,C2_PRODUTO ,CBH.CBH_HRINI

END

