USE [DADOSPRO]
GO
/****** Object:  StoredProcedure [dbo].[SP_REL_PCP_SINTETICO_APONTAMENTO_HORAS]    Script Date: 10/08/2021 12:14:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/******************************************************************************
* PROCEDURE : SP_REL_PCP_SINTETICO_APONTAMENTO_HORAS						  *
* OBJETIVO  : Relatorio de comissao paga por representante com IR			  *
* AUTOR     : Carlos Torres                                                   *
* DATA      : 30/01/2017                                                      *
* OBSERVACAO: Procedure usada para transmitir o demonstrativo de pagamento    * 
*               PARA PROTHEUS                                                 *
*---------------------------------ALTERACOES----------------------------------*
* DATA       AUTOR       OBJETIVO                                             *
*----------- ----------- -----------------------------------------------------*
* EXEC SP_REL_PCP_SINTETICO_APONTAMENTO_HORAS '20161223', '02',''        *
******************************************************************************/
ALTER PROCEDURE [dbo].[SP_REL_PCP_SINTETICO_APONTAMENTO_HORAS]
		@CDATAPONT VARCHAR(10),
		@CFILIAL VARCHAR(02),
		@COPERADOR VARCHAR(06)
AS
BEGIN

	IF ISNULL(OBJECT_ID('TEMP_CT_CBH_SINTETICO'), 0) <> 0
	BEGIN
		DROP TABLE TEMP_CT_CBH_SINTETICO
	END
		
	/*
		Matriz do Relatório
	*/
	CREATE TABLE TEMP_CT_CBH_SINTETICO
	(
		CBH_DATAAPO VARCHAR(10),
		CBH_HORRANG	VARCHAR(07),
		CBH_CELULA	VARCHAR(10),
		CBH_IDOPE01	VARCHAR(20),
		CBH_IDOPE02	VARCHAR(20),
		CBH_IDOPE03	VARCHAR(20),
		CBH_IDOPE04	VARCHAR(20),
		CBH_IDOPE05	VARCHAR(20),
		CBH_IDOPE06	VARCHAR(20),
		CBH_PRODUZ1	INT,
		CBH_PRODUZ2	INT,
		CBH_PRODUZ3	INT,
		CBH_PRODUZ4	INT,
		CBH_PRODUZ5	INT,
		CBH_PRODUZ6	INT,
		CBH_IDLIDER	VARCHAR(20),
		CBH_QTOPERA INT,
		CBH_PRODUTO	VARCHAR(15),
		CBH_PRODUZ	INT
	)

	IF ISNULL(OBJECT_ID('TEMP_CT_CBH_APONTAMENTO'), 0) <> 0
	BEGIN
		DROP TABLE TEMP_CT_CBH_APONTAMENTO
	END
	/*
	Tabela de apoio acumuladora
	*/
	CREATE TABLE TEMP_CT_CBH_APONTAMENTO
	(
		CBH_DATAAPO VARCHAR(10),
		CBH_HORRANG	VARCHAR(07),
		CBH_CELULA	VARCHAR(10),
		CBH_IDOPERA	VARCHAR(06),
		CBH_NOMEOPE	VARCHAR(20),
		CBH_QTOPERA INT,
		CBH_PRODUTO	VARCHAR(15),
		CBH_PRODUZ	INT,
		CBH_IDLIDER	VARCHAR(20)
	)

	INSERT INTO TEMP_CT_CBH_APONTAMENTO
	(
		CBH_DATAAPO ,
		CBH_HORRANG	,
		CBH_CELULA	,
		CBH_IDOPERA	,
		CBH_NOMEOPE	,
		CBH_QTOPERA ,
		CBH_PRODUTO	,
		CBH_PRODUZ	,
		CBH_IDLIDER	

	)
		SELECT 
			CONVERT(VARCHAR(10),CONVERT(DATETIME,CBH_DTFIM),103) AS CBH_DATAAPO
			,CASE 
				WHEN CBH_HRFIM>'00:00' AND CBH_HRFIM<='08:00' THEN '07h-08h' 
				WHEN CBH_HRFIM>'08:00' AND CBH_HRFIM<='09:00' THEN '08h-09h' 
				WHEN CBH_HRFIM>'09:00' AND CBH_HRFIM<='10:00' THEN '09h-10h' 
				WHEN CBH_HRFIM>'10:00' AND CBH_HRFIM<='11:00' THEN '10h-11h' 
				WHEN CBH_HRFIM>'11:00' AND CBH_HRFIM<='12:00' THEN '11h-12h' 
				WHEN CBH_HRFIM>'12:00' AND CBH_HRFIM<='13:00' THEN '12h-13h' 
				WHEN CBH_HRFIM>'13:00' AND CBH_HRFIM<='14:00' THEN '13h-14h' 
				WHEN CBH_HRFIM>'14:00' AND CBH_HRFIM<='15:00' THEN '14h-15h' 
				WHEN CBH_HRFIM>'15:00' AND CBH_HRFIM<='16:00' THEN '15h-16h' 
				WHEN CBH_HRFIM>'16:00' AND CBH_HRFIM<='17:00' THEN '16h-17h' 
				WHEN CBH_HRFIM>'17:00' AND CBH_HRFIM<='18:00' THEN '17h-18h' 
				WHEN CBH_HRFIM>'18:00' AND CBH_HRFIM<='19:00' THEN '18h-19h' 
				WHEN CBH_HRFIM>'19:00' AND CBH_HRFIM<='20:00' THEN '19h-20h' 
				ELSE '' 
				END AS CBH_HORRANG
			--,DATEDIFF(minute ,CONVERT(DATETIME,CBH_DTFIM) + CBH_HRINI ,CONVERT(DATETIME,CBH_DTFIM) + CBH_HRFIM ) AS CBH_MINUTOS
			,CBH_RECUR	AS CBH_CELULA	
			,CBH_OPERAD AS CBH_IDOPERA	
			,SUBSTRING(CB1_NOME,1,CHARINDEX(' ',CB1_NOME,1)) AS CBH_NOMEOPE	
			,0			AS CBH_QTOPERA
			,C2_PRODUTO AS CBH_PRODUTO
			,CBH_QTD	AS CBH_PRODUZ
			,''			AS CBH_IDLIDER	
			--,CBH.*

		FROM CBH040 CBH WITH(NOLOCK)
		INNER JOIN CB1040 CB1 WITH(NOLOCK)
			ON CB1_FILIAL=CBH_FILIAL
			AND CB1.D_E_L_E_T_=''
			AND CB1_CODOPE=CBH_OPERAD
		INNER JOIN SC2040 SC2 WITH(NOLOCK)
			ON C2_FILIAL=CBH_FILIAL
			AND SC2.D_E_L_E_T_=''
			AND LEFT(CBH_OP,6)=C2_NUM
			AND RIGHT(LEFT(CBH_OP,8),2)=C2_ITEM
			AND RIGHT(RTRIM(LTRIM(CBH_OP)),3)=C2_SEQUEN
		WHERE CBH_FILIAL=@CFILIAL
			AND CBH.D_E_L_E_T_='' 
			AND CBH_DTFIM	=	@CDATAPONT 
			AND CBH_TRANSA	=	'02'
			AND CBH_OPERAC	=	'01'
			AND (CBH_OPERAD	=	@COPERADOR OR (@COPERADOR='' AND CBH_OPERAD!='') )

	DECLARE @CDATAANT VARCHAR(10)
	DECLARE @CHORRANT VARCHAR(07)
	DECLARE @CCELUANT VARCHAR(10)
	DECLARE @CPRODANT VARCHAR(15)
	DECLARE @NCONTAB INT
	DECLARE @NOPERA  INT

	SET @NCONTAB = 0
	SET @NOPERA = 0

	DECLARE Estrutura_Cursor CURSOR FOR
		SELECT 
			CBH_DATAAPO ,
			CBH_HORRANG	,
			CBH_CELULA	,
			CBH_IDOPERA	,
			CBH_NOMEOPE	,
			CBH_QTOPERA ,
			CBH_PRODUTO	,
			CBH_IDLIDER ,
			SUM(CBH_PRODUZ) AS CBH_PRODUZ
		FROM TEMP_CT_CBH_APONTAMENTO
		GROUP BY CBH_DATAAPO, CBH_HORRANG, CBH_CELULA, CBH_IDOPERA, CBH_NOMEOPE, CBH_QTOPERA, CBH_PRODUTO, CBH_IDLIDER 
		ORDER BY CBH_DATAAPO, CBH_PRODUTO, CBH_CELULA, CBH_HORRANG

	OPEN Estrutura_Cursor;

	DECLARE @CDATAAPO	VARCHAR(10)
	DECLARE @CHORRANG	VARCHAR(07)
	DECLARE @CCELULA	VARCHAR(10)
	DECLARE @CIDOPERA	VARCHAR(06)
	DECLARE @CNOMEOPE	VARCHAR(20)
	DECLARE @NQTOPERA	INT
	DECLARE @CPRODUTO	VARCHAR(15)
	DECLARE @NPRODUZ	INT
	DECLARE @CIDLIDER	VARCHAR(20)

	FETCH NEXT FROM Estrutura_Cursor INTO @CDATAAPO,@CHORRANG,@CCELULA,@CIDOPERA,@CNOMEOPE,@NQTOPERA,@CPRODUTO,@CIDLIDER,@NPRODUZ;
	WHILE @@FETCH_STATUS = 0
	  BEGIN
		SET @CDATAANT = @CDATAAPO 
		SET @CHORRANT = @CHORRANG 
		SET @CCELUANT = @CCELULA
		SET @CPRODANT = @CPRODUTO
		SET @NCONTAB  = @NCONTAB + 1
		
		IF @NCONTAB = 1
		BEGIN 
			SET @NOPERA   = @NOPERA + 1
			INSERT INTO TEMP_CT_CBH_SINTETICO 
			(	CBH_DATAAPO 
				,CBH_HORRANG	
				,CBH_CELULA	
				,CBH_IDOPE01	
				,CBH_IDLIDER	
				,CBH_QTOPERA 
				,CBH_PRODUTO	
				,CBH_PRODUZ1
				,CBH_PRODUZ
			) 
			SELECT @CDATAAPO	
					,@CHORRANG	
					,@CCELULA	
					,@CNOMEOPE	
					,@CIDLIDER	
					,@NOPERA	
					,@CPRODUTO	
					,@NPRODUZ
					,@NPRODUZ
		END
		
		IF @NCONTAB = 2
		BEGIN 
			SET @NOPERA   = @NOPERA + 1
			UPDATE AUX SET
				CBH_IDOPE02		= @CNOMEOPE
				,CBH_IDLIDER	= @CIDLIDER
				,CBH_QTOPERA	= @NOPERA
				,CBH_PRODUZ2	= @NPRODUZ
				,CBH_PRODUZ		= ISNULL(CBH_PRODUZ,0) + @NPRODUZ
			FROM TEMP_CT_CBH_SINTETICO AUX
			WHERE CBH_DATAAPO=@CDATAAPO 
			AND CBH_HORRANG=@CHORRANG
			AND CBH_CELULA=@CCELULA
			AND CBH_PRODUTO=@CPRODUTO
		END
		
		IF @NCONTAB = 3
		BEGIN 
			SET @NOPERA   = @NOPERA + 1
			UPDATE AUX SET
				CBH_IDOPE03		= @CNOMEOPE
				,CBH_IDLIDER	= @CIDLIDER
				,CBH_QTOPERA	= @NOPERA
				,CBH_PRODUTO	= @CPRODUTO
				,CBH_PRODUZ3	= @NPRODUZ
				,CBH_PRODUZ		= ISNULL(CBH_PRODUZ,0) + @NPRODUZ
			FROM TEMP_CT_CBH_SINTETICO AUX
			WHERE CBH_DATAAPO=@CDATAAPO 
			AND CBH_HORRANG=@CHORRANG
			AND CBH_CELULA=@CCELULA
			AND CBH_PRODUTO=@CPRODUTO
		END

		
		IF @NCONTAB = 4
		BEGIN 
			SET @NOPERA   = @NOPERA + 1
			UPDATE AUX SET
				CBH_IDOPE04		= @CNOMEOPE
				,CBH_IDLIDER	= @CIDLIDER
				,CBH_QTOPERA	= @NOPERA
				,CBH_PRODUTO	= @CPRODUTO
				,CBH_PRODUZ4	= @NPRODUZ
				,CBH_PRODUZ		= ISNULL(CBH_PRODUZ,0) + @NPRODUZ
			FROM TEMP_CT_CBH_SINTETICO AUX
			WHERE CBH_DATAAPO=@CDATAAPO 
			AND CBH_HORRANG=@CHORRANG
			AND CBH_CELULA=@CCELULA
			AND CBH_PRODUTO=@CPRODUTO
		END
		
		IF @NCONTAB = 5
		BEGIN 
			SET @NOPERA   = @NOPERA + 1
			UPDATE AUX SET
				CBH_IDOPE05		= @CNOMEOPE
				,CBH_IDLIDER	= @CIDLIDER
				,CBH_QTOPERA	= @NOPERA
				,CBH_PRODUTO	= @CPRODUTO
				,CBH_PRODUZ5	= @NPRODUZ
				,CBH_PRODUZ		= ISNULL(CBH_PRODUZ,0) + @NPRODUZ
			FROM TEMP_CT_CBH_SINTETICO AUX
			WHERE CBH_DATAAPO=@CDATAAPO 
			AND CBH_HORRANG=@CHORRANG
			AND CBH_CELULA=@CCELULA
			AND CBH_PRODUTO=@CPRODUTO
		END
		
		IF @NCONTAB = 6
		BEGIN 
			SET @NOPERA   = @NOPERA + 1
			UPDATE AUX SET
				CBH_IDOPE06		= @CNOMEOPE
				,CBH_IDLIDER	= @CIDLIDER
				,CBH_QTOPERA	= @NOPERA
				,CBH_PRODUTO	= @CPRODUTO
				,CBH_PRODUZ6	= @NPRODUZ
				,CBH_PRODUZ		= ISNULL(CBH_PRODUZ,0) + @NPRODUZ
			FROM TEMP_CT_CBH_SINTETICO AUX
			WHERE CBH_DATAAPO=@CDATAAPO 
			AND CBH_HORRANG=@CHORRANG
			AND CBH_CELULA=@CCELULA
			AND CBH_PRODUTO=@CPRODUTO
		END
		FETCH NEXT FROM Estrutura_Cursor
		INTO @CDATAAPO,@CHORRANG,@CCELULA,@CIDOPERA,@CNOMEOPE,@NQTOPERA,@CPRODUTO,@CIDLIDER,@NPRODUZ
		
		IF (NOT (@CDATAAPO=@CDATAANT AND @CHORRANG=@CHORRANT AND @CCELULA=@CCELUANT)) OR @CPRODUTO != @CPRODANT
		BEGIN
			SET @NCONTAB = 0
			SET @NOPERA  = 0
		END
	END;
	-- fim do cursor
	CLOSE Estrutura_Cursor;
	DEALLOCATE Estrutura_Cursor;


	SELECT 
		AUX.CBH_DATAAPO 
		,AUX.CBH_HORRANG	
		,AUX.CBH_CELULA	
		,AUX.CBH_IDOPE01 AS CBH_ID01
		,AUX.CBH_IDOPE02 AS CBH_ID02	
		,AUX.CBH_IDOPE03 AS CBH_ID03
		,AUX.CBH_IDOPE04 AS CBH_ID04
		,AUX.CBH_IDOPE05 AS CBH_ID05
		,AUX.CBH_IDOPE06 AS CBH_ID06
		,AUX.CBH_PRODUZ1 AS CBH_PRO1
		,AUX.CBH_PRODUZ2 AS CBH_PRO2
		,AUX.CBH_PRODUZ3 AS CBH_PRO3
		,AUX.CBH_PRODUZ4 AS CBH_PRO4
		,AUX.CBH_PRODUZ5 AS CBH_PRO5
		,AUX.CBH_PRODUZ6 AS CBH_PRO6
		,AUX.CBH_IDLIDER	
		,AUX.CBH_QTOPERA 
		,AUX.CBH_PRODUTO	
		,AUX.CBH_PRODUZ	
		,B1_DESC AS NOME_PRODUTO
		,0 AS CBH_MTABH
		,0 AS CBH_MTPAD
	FROM TEMP_CT_CBH_SINTETICO AUX
	INNER JOIN SB1040 SB1 WITH(NOLOCK)
	ON B1_FILIAL=@CFILIAL
	AND SB1.D_E_L_E_T_=''
	AND B1_COD=CBH_PRODUTO
	ORDER BY CBH_DATAAPO,CBH_CELULA,CBH_PRODUTO,CBH_HORRANG

END
