USE [DADOSPRO]
GO
/****** Object:  StoredProcedure [dbo].[SP_REL_DIVERGENCIA_SBFSB2]    Script Date: 27/07/2021 16:53:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/******************************************************************************
* PROCEDURE : SP_REL_DIVERGENCIA_SBFSB2         							  *
* OBJETIVO  : Lista produtos com desbalanceamento de saldos SB2 e SBF		  *
* AUTOR     : Carlos Torres                                                   *
* DATA      : 11/01/2017                                                      *
* OBSERVACAO: Procedure usada em MTA410T.PRW								  * 
*																			  *
*---------------------------------ALTERACOES----------------------------------*
* DATA       AUTOR       OBJETIVO                                             *
*----------- ----------- -----------------------------------------------------*
 EXEC SP_REL_DIVERGENCIA_SBFSB2 'TAIFF    ' , '085749' , '22' , '02' 
 EXEC SP_REL_DIVERGENCIA_SBFSB2 'TAIFF' , '085749' , '22' , '02' 
 SELECT * FROM SC9030 WHERE C9_PEDIDO='085749' AND C9_FILIAL='02' AND C9_NFISCAL='' AND D_E_L_E_T_=''
******************************************************************************/
ALTER PROCEDURE [dbo].[SP_REL_DIVERGENCIA_SBFSB2]
	@CMARCA VARCHAR(06),
	@CPEDIDO VARCHAR(06),
	@CARMAZEM VARCHAR(02),
	@CFILIAL VARCHAR(02)
	
AS
BEGIN

	--DECLARE @CMARCA VARCHAR(06)
	--DECLARE SELECT C6_PRODUTO FROM SC6030 SC6 WITH(NOLOCK) WHERE C6_FILIAL=@CFILIAL AND C6_NUM=@CPEDIDO VARCHAR(500)
	--DECLARE @CARMAZEM VARCHAR(02)
	--DECLARE @CFILIAL VARCHAR(02)

	--SET SELECT C6_PRODUTO FROM SC6030 SC6 WITH(NOLOCK) WHERE C6_FILIAL=@CFILIAL AND C6_NUM=@CPEDIDO	=	'000000034'
	--SET @CMARCA			=	'TAIFF '
	--SET @CARMAZEM		=	'22'
	--SET @CFILIAL		=	'02'
	SELECT C6_PRODUTO 
	INTO #TEMP_CT_SC6030_SBFSB2
	FROM SC6030 SC6 WITH(NOLOCK) 
	WHERE C6_FILIAL=@CFILIAL AND C6_NUM=@CPEDIDO AND SC6.D_E_L_E_T_=''
	
	SELECT 
		MARCA,
		PRODUTO,
		SALDO_a21__,
		SALDO_a22__,
		RESERVA_a21,
		RESERVA_a22,
		LIBERADO_a21,
		LIBERADO_a22,
		CTRLRES_a21,
		CTRLRES_a22
	INTO #TEMP_CT_TAIFF_SB2
	FROM 
	(
		SELECT 
			@CMARCA + ' - SB2'		AS MARCA,
			PRODUTO					AS PRODUTO,
			SUM(B2_QATU_VUM)		AS SALDO_a21__,
			SUM(B2_QATU_VDOS)		AS SALDO_a22__,
			SUM(B2_RESERVA_VUM)		AS RESERVA_a21,
			SUM(B2_RESERVA_VDOS)	AS RESERVA_a22,
			SUM(C9_LIBERADO_VUM)	AS LIBERADO_a21,
			SUM(C9_LIBERADO_VDOS)	AS LIBERADO_a22,
			SUM(C0_RESERVA_VUM)		AS CTRLRES_a21,
			SUM(C0_RESERVA_VDOS)	AS CTRLRES_a22
		FROM 
		(
			SELECT
				B2_COD			AS PRODUTO,
				0				AS B2_QATU_VUM, 
				SUM(B2_QATU)	AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				SUM(B2_RESERVA) AS B2_RESERVA_VDOS,
				0				AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SB2030 SB2 WITH(NOLOCK) WHERE B2_FILIAL=@CFILIAL AND SB2.D_E_L_E_T_='' AND B2_LOCAL IN (@CARMAZEM) AND B2_COD IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2)
			GROUP BY B2_COD
		UNION ALL
			SELECT 
				B2_COD			AS PRODUTO,
				SUM(B2_QATU)	AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				SUM(B2_RESERVA) AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				0				AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SB2030 SB2 WITH(NOLOCK) WHERE B2_FILIAL=@CFILIAL AND SB2.D_E_L_E_T_='' AND B2_LOCAL IN ('21') AND B2_COD IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2)
			GROUP BY B2_COD
		UNION ALL
			SELECT 
				C9_PRODUTO		AS PRODUTO,
				0				AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				SUM(C9_QTDLIB)	AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SC9030 SC9 WITH(NOLOCK) WHERE C9_FILIAL=@CFILIAL AND SC9.D_E_L_E_T_='' AND C9_LOCAL IN ('21') AND C9_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2) AND C9_NFISCAL=''
			GROUP BY C9_PRODUTO
		UNION ALL
			SELECT 
				C9_PRODUTO		AS PRODUTO,
				0				AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				0				AS C9_LIBERADO_VUM,
				SUM(C9_QTDLIB)	AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SC9030 SC9 WITH(NOLOCK) WHERE C9_FILIAL=@CFILIAL AND SC9.D_E_L_E_T_='' AND C9_LOCAL IN (@CARMAZEM) AND C9_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2) AND C9_NFISCAL=''
			GROUP BY C9_PRODUTO
		UNION ALL
			SELECT 
				C0_PRODUTO		AS PRODUTO,
				0				AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				0				AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				SUM(C0_QUANT)	AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SC0030 SC0 WITH(NOLOCK) WHERE C0_FILIAL=@CFILIAL AND SC0.D_E_L_E_T_='' AND C0_LOCAL IN ('21') AND C0_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2) AND C0_QUANT!=0
			GROUP BY C0_PRODUTO
		UNION ALL
			SELECT 
				C0_PRODUTO		AS PRODUTO,
				0				AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				0				AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				SUM(C0_QUANT)	AS C0_RESERVA_VDOS
			FROM SC0030 SC0 WITH(NOLOCK) WHERE C0_FILIAL=@CFILIAL AND SC0.D_E_L_E_T_='' AND C0_LOCAL IN (@CARMAZEM) AND C0_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2) AND C0_QUANT!=0
			GROUP BY C0_PRODUTO
		) AUX
		GROUP BY PRODUTO

		UNION ALL
		SELECT
			@CMARCA + ' - SBF'		AS MARCA,
			PRODUTO					AS PRODUTO,
			SUM(BF_QUANT_VUM)		AS SALDO_a21__,
			SUM(BF_QUANT_VDOS)		AS SALDO_a22__,
			SUM(BF_EMPENHO_VUM)		AS RESERVA_a21,
			SUM(BF_EMPENHO_VDOS)	AS RESERVA_a22,
			SUM(C9_LIBERADO_VUM)	AS LIBERADO_a21,
			SUM(C9_LIBERADO_VDOS)	AS LIBERADO_a22,
			SUM(C0_RESERVA_VUM)		AS CTRLRES_a21,
			SUM(C0_RESERVA_VDOS)	AS CTRLRES_a22
		FROM
		(
			SELECT 
				BF_PRODUTO		AS PRODUTO,
				0				AS BF_QUANT_VUM,
				0				AS BF_EMPENHO_VUM,
				SUM(BF_QUANT)	AS BF_QUANT_VDOS,
				SUM(BF_EMPENHO) AS BF_EMPENHO_VDOS,
				0				AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SBF030 SBF WITH(NOLOCK) WHERE BF_FILIAL=@CFILIAL AND SBF.D_E_L_E_T_='' AND BF_LOCAL IN (@CARMAZEM) AND BF_QUANT!=0 AND BF_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2)
			GROUP BY BF_PRODUTO
		UNION ALL
			SELECT 
				BF_PRODUTO		AS PRODUTO,
				SUM(BF_QUANT)	AS BF_QUANT_VUM,
				SUM(BF_EMPENHO) AS BF_EMPENHO_VUM,
				0				AS BF_QUANT_VDOS,
				0				AS BF_EMPENHO_VDOS,
				0				AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SBF030 SBF WITH(NOLOCK) WHERE BF_FILIAL=@CFILIAL AND SBF.D_E_L_E_T_='' AND BF_LOCAL IN ('21') AND BF_QUANT!=0 AND BF_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2)
			GROUP BY BF_PRODUTO
		UNION ALL
			SELECT 
				C9_PRODUTO		AS PRODUTO,
				0				AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				SUM(C9_QTDLIB)	AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SC9030 SC9 WITH(NOLOCK) WHERE C9_FILIAL=@CFILIAL AND SC9.D_E_L_E_T_='' AND C9_LOCAL IN ('21') AND C9_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2) AND C9_NFISCAL=''
			GROUP BY C9_PRODUTO
		UNION ALL
			SELECT 
				C9_PRODUTO		AS PRODUTO,
				0				AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				0				AS C9_LIBERADO_VUM,
				SUM(C9_QTDLIB)	AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SC9030 SC9 WITH(NOLOCK) WHERE C9_FILIAL=@CFILIAL AND SC9.D_E_L_E_T_='' AND C9_LOCAL IN (@CARMAZEM) AND C9_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2) AND C9_NFISCAL=''
			GROUP BY C9_PRODUTO
		UNION ALL
			SELECT 
				C0_PRODUTO		AS PRODUTO,
				0				AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				0				AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				SUM(C0_QUANT)	AS C0_RESERVA_VUM,
				0				AS C0_RESERVA_VDOS
			FROM SC0030 SC0 WITH(NOLOCK) WHERE C0_FILIAL=@CFILIAL AND SC0.D_E_L_E_T_='' AND C0_LOCAL IN ('21') AND C0_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2) AND C0_QUANT!=0
			GROUP BY C0_PRODUTO
		UNION ALL
			SELECT 
				C0_PRODUTO		AS PRODUTO,
				0				AS B2_QATU_VUM, 
				0				AS B2_QATU_VDOS,
				0				AS B2_RESERVA_VUM, 
				0				AS B2_RESERVA_VDOS,
				0				AS C9_LIBERADO_VUM,
				0				AS C9_LIBERADO_VDOS,
				0				AS C0_RESERVA_VUM,
				SUM(C0_QUANT)	AS C0_RESERVA_VDOS
			FROM SC0030 SC0 WITH(NOLOCK) WHERE C0_FILIAL=@CFILIAL AND SC0.D_E_L_E_T_='' AND C0_LOCAL IN (@CARMAZEM) AND C0_PRODUTO IN (SELECT C6_PRODUTO FROM #TEMP_CT_SC6030_SBFSB2) AND C0_QUANT!=0
			GROUP BY C0_PRODUTO
		) AUX
		GROUP BY PRODUTO
	) TEMP


	SELECT 
		SB2.PRODUTO
		,SB2.SALDO_a21__ AS SLDSB221
		,SBF.SALDO_a21__ AS SLDSBF21
		,SB2.RESERVA_a21 AS RSVSB221
		,SBF.RESERVA_a21 AS RSVSBF21
		,SB2.SALDO_a22__ AS SLDSB222
		,SBF.SALDO_a22__ AS SLDSBF22
		,SB2.RESERVA_a22 AS RSVSB222
		,SBF.RESERVA_a22 AS RSVSBF22
	FROM #TEMP_CT_TAIFF_SB2 SB2
	INNER JOIN #TEMP_CT_TAIFF_SB2 SBF
	ON SB2.PRODUTO=SBF.PRODUTO 
	AND SBF.MARCA=@CMARCA + ' - SBF'
	WHERE SB2.MARCA=@CMARCA + ' - SB2'
	AND (
			SB2.SALDO_a21__ != SBF.SALDO_a21__
			OR	SB2.SALDO_a22__!=SBF.SALDO_a22__
			OR	SB2.RESERVA_a21!=SBF.RESERVA_a21
			OR	SB2.RESERVA_a22!=SBF.RESERVA_a22
			--OR	SB2.LIBERADO_a21!=SBF.LIBERADO_a21
			--OR	SB2.LIBERADO_a22!=SBF.LIBERADO_a22
			--OR	SB2.CTRLRES_a21!=SBF.CTRLRES_a21
			--OR	SB2.CTRLRES_a22!=SBF.CTRLRES_a22
		)

END
